### ISSUE TITLE
Links in not working in Multi-level Menu

### ISSUE THREAD

**Issue by redrhinomedia** [daneWilliams/jquery.dropdown#14]
I have a multi-level menu built with an unordered list. At the final, bottom level I have links to pdfs, but the links don't work. Is there something I am missing? Some of my code is below:

HTML:

```
<ul class="instruct" style="margin: 0 5px 10px;">
  <li data-dropdown-text="Classic Kits">
    <ul>
      <li data-dropdown-text="Buick">
        <ul>
          <li data-dropdown-text="GSX">
            <ul>
              <li data-dropdown-text="64-72">
                <ul>
                  <li data-dropdown-text="Bags & Brackets">
                    <ul>
                      <li><a href="/assets/images/EZ%20Instructions/ABG%20Front%20Install.pdf">Front</a></li>
```

JS:
I have the default options initialized inside.
$('select, ul.instruct').dropdown();

**Comment by zatchgordon** [comment]
I think the li element should have the href on it, not the 'a' element,

`<li href="/assets/images/EZ%20Instructions/ABG%20Front%20Install.pdf">Front</li>`

**Comment by daneWilliams** [comment]
If you add `"data-dropdown-selectable="false"` to the parent `li`, it will allow the link to be clickable. 

This would be better if it was automatic though, I'll work it into the next version.

**Comment by daneWilliams** [comment]
Also, you can add multiple data attributes as a single attribute, e.g. `data-dropdown="{ 'text':'Bags & Brackets', 'selectable':false }"`
