### ISSUE TITLE
Selected Item

### ISSUE THREAD

**Issue by faravaghi** [daneWilliams/jquery.dropdown#15]
How can get Selected item in ul element?
or can you insert event for this plugin? for example change menu, selected or ...

**Comment by zatchgordon** [comment]
It sounds like you're asking for a callback for when an item in the drop down is selected.
This is how I created a callback.

In the defaults section of the plugin I added a callback called onOptionSelect

```
defaults: {
            //callBack
added this--->  onOptionSelect: function(opt){return false;}, 
            // Animation
            animate: true,
            speed: 300,

            // Auto
            autoClose: true,
```

And then in the "toggleText" function where it sets the .html() to "text" i added a call to the onOptionSelect 

```
if ( text ) {

                elem.toggleText.html( text );
    added this--->  self.options.onOptionSelect( text);

            } else {

                elem.toggleText.html( elem.toggleButton.data( 'dropdown-text' ) );
      added this--->    self.options.onOptionSelect( text);

            }
```

now in the code where you call the plugin $('ul').dropdown you can add the parameter of onOptionSelect: function(value){}

```
$(element).dropdown({
                        selectParents: false,
                        toggleText: "\&nbsp; ",
   added this--->onOptionSelect: function (value) {
                                  //here this will return the value of the selected item 
                                 //and then you can do whatever you want with it
                            }
```

**Comment by daneWilliams** [comment]
This can actually be achieved with events. Before you initialise your dropdown, use this bit of code;

$('ul').on( 'dropdown-before-select', function( e, item, previous, dropdown ) {



});

**Comment by daneWilliams** [comment]
This can actually be achieved with events. Before you initialise your dropdown, use this bit of code;

```
$('ul').on( 'dropdown-before-select', function( e, item, previous, dropdown ) {

    // Do stuff here

});
```

`item` contains the item object about to be selected, `previous` contains the currently selected item and `dropdown` refers to the current dropdown instance.

Other events are also available. To fire just before or after a menu is opened for example;

```
$('ul').on( 'dropdown-before-open-menu', function( e, target, current, dropdown ) {

    // Do stuff here

});

$('ul').on( 'dropdown-after-open-menu', function( e, menu, previous, dropdown ) {

    // Do stuff here

});
```

`menu` contains the menu object about to be opened, `previous` contains the currently open menu and `dropdown` refers to the current dropdown instance.

Opening/closing the dropdown;

```
$('ul').on( 'dropdown-before-open', function( e, dropdown ) {

    // Do stuff here

});

$('ul').on( 'dropdown-after-close', function( e, dropdown ) {

    // Do stuff here

});
```

I'll improve the documentation and event management for v2.

**Comment by zatchgordon** [comment]
So I've been playing around with your suggestion to use the $('ul').on("dropdown-before-select")

Here's the biggest problem I'm having: sometimes I would like to have an object stored.

The `item` object returned has text, which is good if all I need is text, but if I'm using it to communicate with a database, I probably need an id.

I can get around this by setting the value to a number then, when returning the item, split the value by the ":" .... var value = item.value.split(":")
now I can check either the string or the actual value to see if it's a number or not.

However, it would be much easier if I could just have a stored value returned. 
Right now on my callback I have three blocks of code 

```
if (isJson(item)) {
      //deal with JSON data
      //JSON.parse(item);
}else if (typeof item === "string") {
     var value = item.split(":");
      if (value[0] === "string") {
            //deal with strings
            //value[1]
       } else if (value[0] === "number") {
             //deal with numbers
            //parseInt(value[1])
       }
 }
```

It'd be super dope if it could just return with the data I'd like to store instead of going through these blocks of code and converting them to the original values

**Comment by daneWilliams** [comment]
@zatchgordon, each item and menu object has a unique ID, available via the `uid` key.

I can't think why it would be returning a text value, but if it is, the object and ID can be retrieved in your callback with the following;
````
var obj = $(element).dropdown( 'getItem', item );
var uid = obj.uid;
````
The item passed to the `getItem` method can either be the text value, unique ID or jQuery selector/object. 

If it's an existing item object, it will just be returned so you wouldn't need your JSON check. If the item cannot be found, it will return `false`.

Apologies for the poor documentation, I am currently updating the Wiki.

**Comment by daneWilliams** [comment]
Additionally, unique IDs can be manually set rather than being generated by the plugin. You would need to add one of the following to your list items;
````
<li data-dropdown-uid="my-id-1">
````
````
<li data-dropdown='{ "uid":"my-id-1" }'>
````
