### ISSUE TITLE
Enable resetting the selected value for multi level control

### ISSUE THREAD

**Issue by ryaa** [daneWilliams/jquery.dropdown#19]
Right now the multi level control allows selecting the value however there is no way to reset it back to none.
For example the second control here http://www.jqueryscript.net/demo/Animated-Multi-level-jQuery-Dropdown-Plugin/

**Comment by daneWilliams** [comment]
This feature will be added to an upcoming update. In the meantime, it could be achieved with the following;

````
$('.dropdown-selected').each(function() {

    $('.dropdown').dropdown( 'deselect', $(this) );

});
````

**Comment by daneWilliams** [comment]
Now fixed with v2.

To deselect all, simply use `$(element).dropdown( 'deselect' )`
