### ISSUE TITLE
How to programmatically change the selected item?

### ISSUE THREAD

**Issue by bertelo** [daneWilliams/jquery.dropdown#20]
After the page (including the dropdown menu) loaded completely I want to change the selected item programmatically. How can we achieve this?

**Comment by daneWilliams** [comment]
After the dropdown has been initialised this can be achieved with any of the following methods;

### Select by list item
```
$('.dropdown').dropdown( 'select', '#list-item-1' );
```
This can be any jQuery selector or object.

---

### Select by value
```
$('.dropdown').dropdown( 'selectValue', 'Some value' );
```

---

### Select by UID
```
$('.dropdown').dropdown( 'select', 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' );
```

UIDs are used to uniquely identify each item and menu. They can be found as a data value on any dropdown item/menu element;

```
$('.dropdown-item').each(function() {

    // Get from data attribute
    var uid = $(this).data( 'dropdown-uid' );

    // Get from item object
    var item = $('.dropdown').dropdown( 'getItem', $(this) );
        uid  = item.uid;

    console.log( uid );

});
```
