### ISSUE TITLE
Select value not sent through a POST form

### ISSUE THREAD

**Issue by douardo** [daneWilliams/jquery.dropdown#7]
Hi,

Thanks a lot for this plugin, it looks very good and works well.
The only problem I have is when I use it through a form. When the form is submitted, the value of my select element is not sent.
I wonder if it is because the select element becomes "display: none" when I use it.

Any suggestion?

Thanks a lot.
Ed

**Comment by daneWilliams** [comment]
Hi Ed,

That's odd, it should be updating the value of the select element every time you make a selection. Being hidden should have no impact.

I'll do some testing and see if there's an underlying issue. In the meantime, could you please provide a sample of the code/markup you are using?

Dane
