### ISSUE TITLE
add a select option like back to select the main category

### ISSUE THREAD

**Issue by hamid2005** [daneWilliams/jquery.dropdown#8]
It doesn't have the ability to allow selecting the main category. It would be nice if it has that ability to select the main category an not go inside a category by selecting it .

**Comment by daneWilliams** [comment]
Agreed, I will implement this feature. Thank you!

**Comment by daneWilliams** [comment]
If the parent item is selectable, or the `selectParents` option is `true`, it will now get added to its child menu as the first item (with a divider) and can be selected
