### ISSUE TITLE
ul or select conflict with my other elements in my site

### ISSUE THREAD

**Issue by hamid2005** [daneWilliams/jquery.dropdown#9]
I'm trying to use the plugin.  When I call:

```
<script>
    $(function() {

        $('select, ul').dropdown();

    });
</script>
```

Both 'select' and 'ul' conflict with my other elements in the site. What's the solution ?

Thanks

**Comment by daneWilliams** [comment]
Hi, could you please provide some example code to show me how you are implementing the dropdown?

**Comment by daneWilliams** [comment]
Hi hamid,

The selector you have used will target ALL `select` and `ul` elements on your page. It is recommended to give the one you wish to target a unique ID or specific class and select that instead, for example;

```
<select id="my-select">
    <option>1</option>
</select>

<select class="dropdown-target">
    <option>1</option>
</select>

<script>
    $(function() {

        $('#my-select').dropdown();
        $('.dropdown-target').dropdown();

    });
</script>
```

Please refer to jQuery documentation for more information on using selectors: https://api.jquery.com/category/selectors/
